language: c
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libluajit-5.1-dev libpcap-dev libev-dev luajit
env:
  global:
   - secure: "NJqhFAJwOlrFs4bezz9ze0+bf3grgCJN5ZMB63gwyCbIk4CsE2xYeAmfXSMbhq2S6j7LjzT21FEPVF652lXrrdAEeYOOhqqV65Tj1AmuMeXjUFPVFOLzERHNjOTjcfGjpV2+n0XTbLaw8jvKsw48CnhTMPt45cohcI5YOehMUR+uxen0yCL6nYo/PLqgBUfFUCHLL7ZIIgdEaPcPhNBaPyCkYmEYFVLuSMdvlOFkx5TxGJz7gQxjN764ik3nJZ+UnjclQ7k8OenWmSHWlwg/Xn92KeWXeJ+IQsMdXjh0vtGXyz9O2DpvUweeAubcB1+1WbFXeiu7ClIFPTfPv/lojDDcX+0abQnuUjRp5rA0iR0PqvobIC+0rXh1wt4kawQkA79a7+OlcDVtoTRII53r14icZYPO7Ajw1nE67JaJ2PHL6NQyMwtsHOfAlBZxNaod784Bs0IX/ML+SKMA1GltqKYKS//jdwbylKqNbQGXoS+echMsWvWWlugJkarrq1bqgKMq7hRwT/ZLrs7stm1naQD3CH8SnsS0tVlX6FQTUNZv+ce8goPM8DIVHhlBujju1bSrD0kHWwJXIuO5n5HUPbN46ox1qdp6/ghF2qJ6IN2h4ooaFrD8SRJUEDZWFuDBaml2YTAjr/rR5fZS0HjxPzBhhk2mUqOSQth9ITT+VNE="
addons:
  coverity_scan:
    project:
      name: "DNS-OARC/dnsjit"
      description: "Build submitted via Travis CI"
    notification_email: lundstrom.jerry@gmail.com
    build_command_prepend: "./autogen.sh && ./configure && make clean"
    build_command: "make"
    branch_pattern: coverity_scan
script: true
